name: Build and Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub (optional)
        run: echo "No DockerHub login - using local build"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: Save Docker image to tarball
        run: |
          docker save ${{ secrets.DOCKER_IMAGE_NAME }} -o app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.tar"
          target: "~/"

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load -i app.tar
            docker stop nginx-app || true
            docker rm nginx-app || true
            docker run -d -p 80:80 --name nginx-app ${{ secrets.DOCKER_IMAGE_NAME }}